"use client";

import { useDeferredValue, useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, Check, ChevronDown, Coins, Copy, Download, Menu, Package, PanelRight, Plus, Printer, RotateCcw, Save, Search, Shield, Sparkles, Swords, Trash2, Upload, UserPlus, Users, X } from "lucide-react";
import {
  ABILITIES, BASE_WEAPONS, CLASS_HIT_DIE, CLASS_SAVE, EQUIPMENT, EXPANSIONS, RARE_LANGUAGES, RULES, SKILL_ABILITY, SPELL_STAT_EFFECTS, STANDARD_LANGUAGES,
  Character, RowEntry, Workspace, allowed, armorClass, armorOptions, automaticFeatures, completeLongRest, completeShortRest, concentrationSaveDifficulty, hasMagicInitiateFeat,
  classes, currentCharacterSpells, defaultWorkspace, featAdvancementNodes, featureBenefits, grantedSpells, initiative, isSummoningSpell, languageRules, maxHp, maximumPreparedSpellLevel, modNumber, normalizeWorkspace, passivePerception, previewHitPointExpression, pricedSpellMaterial, proficiency, resourceCaps, sanitizeLanguageSelections, sanitizeManualFeatures,
  shieldOptions, sidebarSwipeAction, signed, skillDisadvantageSources, skillTrainingBonus, speedValue, spellcastingAbility, spellListClass, spellSchool, spellSelectionLimits, spellSlots, summonStats, uid, wizardSpellbookContains, wizardSpellbookEntries, wizardSpellbookSlots, wizardSpellbookSpells, weaponAttackResolution, exhaustionD20Penalty, CONDITION_DEFINITIONS, setCondition, normalizeExhaustion, MAGIC_INITIATE_LISTS, DIVINE_ORDERS, PRIMAL_ORDERS, alternateFightingStyleFor, grantedCantripChoices
} from "./ipad-model";

const STORE="juance-web-workspace-v3";
const BACKUP_STORE="juance-web-workspace-v3-backup";
const sourceLabel=(level:number)=>level===0?"戏法":`${level}环`;
const spellMeta=(text:string,label:string)=>text.match(new RegExp(`${label}[：:]?\\s*([^\\n]+)`))?.[1]?.trim()||"—";
const spellDamage=(text:string,characterLevel=1)=>{const description=text.replace(/[\r\n]+/g," ");const scales=[...description.matchAll(/(\d{1,2})级\s*[（(]\s*([^）)]*?\d+d\d+[^）)]*?)[）)]/g)].map(x=>({level:Number(x[1]),dice:x[2].match(/\d+d\d+(?:\s*[+＋]\s*\d+d\d+)*/i)?.[0]})).filter(x=>x.dice&&x.level<=characterLevel).sort((a,b)=>b.level-a.level);if(scales[0]?.dice)return scales[0].dice.replace(/\s/g,"").replaceAll("＋","+");const damage=[...description.matchAll(/(\d+d\d+(?:\s*[+＋]\s*\d+d\d+)?)[^。；]{0,24}?(?:点)?[^。；]{0,8}?伤害/gi)].map(x=>x[1].replace(/\s/g,"").replaceAll("＋","+"));return [...new Set(damage)].slice(0,3).join(" / ")||"—"};
const spellSave=(text:string,characterLevel=1)=>{const description=text.replace(/[\r\n]+/g," ");const ability=description.match(/(力量|敏捷|体质|智力|感知|魅力)\s*豁免/)?.[1];if(!ability)return "—";const damage=spellDamage(description,characterLevel);if(damage==="—")return `${ability}豁免`;if(/一半伤害|伤害减半|半数伤害|一半的伤害|只(?:会)?承受一半|仅受到一半|只受到上述伤害的一半/.test(description))return `${ability}｜失败 ${damage}｜成功 ${damage}÷2`;if(/豁免成功[^。；]{0,24}(?:不受|不会受到|免受)[^。；]{0,8}伤害/.test(description)||description.includes("否则将受到")||description.includes("若失败")||/豁免(?:检定)?失败/.test(description))return `${ability}｜失败 ${damage}｜成功 0`;return `${ability}｜伤害 ${damage}`};

function NumberBox({value,onChange,min=0,max=99,label}:{value:number;onChange:(n:number)=>void;min?:number;max?:number;label:string}){
  const selectOnPointerUp=useRef(false);
  const numericDraft=(text:string)=>text.replace(/[０-９]/g,digit=>String.fromCharCode(digit.charCodeAt(0)-0xfee0)).replace(/[^0-9]/g,"");
  const commit=(input:HTMLInputElement)=>{const parsed=Number.parseInt(input.value,10);const next=Math.max(min,Math.min(max,Number.isFinite(parsed)?parsed:min));input.value=String(next);if(next!==value)onChange(next)};
  return <input key={value} className="number-box" aria-label={label} inputMode="numeric" enterKeyHint="done" type="text" pattern="[0-9]*" defaultValue={value}
    onFocus={event=>{selectOnPointerUp.current=true;event.currentTarget.select()}}
    onPointerUp={event=>{if(selectOnPointerUp.current){event.preventDefault();event.currentTarget.select();selectOnPointerUp.current=false}}}
    onChange={event=>{event.currentTarget.value=numericDraft(event.currentTarget.value)}}
    onBlur={event=>commit(event.currentTarget)}
    onKeyDown={event=>{if(event.key==="Enter")event.currentTarget.blur();else if(event.key==="Escape"){event.currentTarget.value=String(value);event.currentTarget.blur()}}}/>;
}
function Section({title,icon,children,action,wide=false}:{title:string;icon?:React.ReactNode;children:React.ReactNode;action?:React.ReactNode;wide?:boolean}){return <section className={`sheet-card ${wide?"wide":""}`}><header className="card-head"><span>{icon}</span><h2>{title}</h2>{action}</header>{children}</section>}
function Segmented({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:Array<[string,string,React.ReactNode]>}){return <div className="segmented" role="tablist">{items.map(([key,label,icon])=><button key={key} role="tab" aria-selected={value===key} className={value===key?"active":""} onClick={()=>onChange(key)}>{icon}<span>{label}</span></button>)}</div>}
function ResourceDots({label,max,used,onChange,unit}:{label:string;max:number;used:number;onChange:(n:number)=>void;unit?:string}){if(unit)return <div className="resource-line"><b>{label}</b><span className="resource-points">{Math.max(0,max-used)} / {max} {unit}</span><button onClick={()=>onChange(Math.max(0,used-1))}>＋</button><button onClick={()=>onChange(Math.min(max,used+1))}>－</button></div>;return <div className="resource-line"><b>{label}</b><div className="dots">{Array.from({length:max},(_,i)=><button key={i} aria-label={`${label} ${i+1}`} className={i<used?"spent":""} onClick={()=>onChange(i<used?i:i+1)}><Check/></button>)}</div></div>}

function WizardSpellbookPanel({c,onChange}:{c:Character;onChange:(spells:RowEntry[])=>void}){
  const slots=useMemo(()=>wizardSpellbookSlots(c),[c]);const entries=wizardSpellbookEntries(c);const bookSpells=wizardSpellbookSpells(c);const limits=spellSelectionLimits(c.className,c.subclass,c.level,c.abilities);
  const groups=useMemo(()=>{const map=new Map<string,{key:string;label:string;slots:ReturnType<typeof wizardSpellbookSlots>}>();for(const slot of slots){const key=`${slot.gainedAtLevel}:${slot.kind.startsWith("subclass")?"subclass":"class"}`;const label=slot.kind==="initial"?"1级 · 初始法术":slot.kind.startsWith("subclass")?`${slot.gainedAtLevel}级 · ${slot.label.split(" · ")[0]}法术`:`${slot.gainedAtLevel}级 · 研究法术`;const group=map.get(key)||{key,label,slots:[]};group.slots.push(slot);map.set(key,group)}return [...map.values()]},[slots]);
  const [groupKey,setGroupKey]=useState(groups.at(-1)?.key||"");const [copyValue,setCopyValue]=useState("");const [prepareValue,setPrepareValue]=useState("");
  const selectedGroup=groups.find(group=>group.key===groupKey)||groups.at(-1);const valueOf=(spell:(typeof RULES.Spells)[number])=>`${spell.Source}\u001f${spell.Name}`;
  const parseSpell=(value:string)=>{const [source,name]=value.split("\u001f");return RULES.Spells.find(spell=>spell.Source===source&&spell.Name===name)};
  const commit=(next:RowEntry[])=>{const draft={...c,spells:next};const validNames=new Set(wizardSpellbookEntries(draft).map(entry=>entry.name));onChange(next.filter(entry=>!["手动准备","法术精通","招牌法术"].includes(entry.spellRole||"")||validNames.has(entry.name)))};
  const setSlot=(slot:ReturnType<typeof wizardSpellbookSlots>[number],value:string)=>{const remaining=c.spells.filter(entry=>!(entry.spellContext==="法师"&&entry.slotKey===slot.key));if(!value){commit(remaining);return}const spell=parseSpell(value);if(!spell)return;if(entries.some(entry=>entry.slotKey!==slot.key&&entry.name===spell.Name)){alert("同名法术已经收入法术书。");return}const role=slot.kind.startsWith("subclass")?"法术书·子职":"法术书·升级";commit([...remaining,{id:uid(),name:spell.Name,detail:`${slot.label} · ${sourceLabel(spell.Level)} · ${spell.Source}`,note:spell.Description,quantity:1,level:spell.Level,source:spell.Source,used:false,spellRole:role,spellContext:"法师",slotKey:slot.key}])};
  const availableForSlot=(slot:ReturnType<typeof wizardSpellbookSlots>[number])=>RULES.Spells.filter(spell=>spell.Level>=slot.minimumSpellLevel&&spell.Level<=slot.maximumSpellLevel&&spell.Classes?.includes("法师")&&allowed(spell.Source,c.enabledSources)&&(!slot.school||spellSchool(spell)===slot.school)).sort((a,b)=>a.Level-b.Level||a.Name.localeCompare(b.Name,"zh-CN"));
  const copyable=RULES.Spells.filter(spell=>spell.Level>=1&&spell.Level<=Math.max(1,Math.floor((c.level+1)/2))&&spell.Classes?.includes("法师")&&allowed(spell.Source,c.enabledSources)&&!entries.some(entry=>entry.name===spell.Name)).sort((a,b)=>a.Level-b.Level||a.Name.localeCompare(b.Name,"zh-CN"));
  const addCopy=()=>{const spell=parseSpell(copyValue);if(!spell)return;commit([...c.spells,{id:uid(),name:spell.Name,detail:`冒险抄录 · ${sourceLabel(spell.Level)} · ${spell.Source}`,note:spell.Description,quantity:1,level:spell.Level,source:spell.Source,used:false,spellRole:"法术书·抄录",spellContext:"法师",slotKey:`spellbook:copy:${uid()}`}]);setCopyValue("")};
  const preparedNames=new Set(c.spells.filter(entry=>entry.spellContext==="法师"&&entry.spellRole==="手动准备").map(entry=>entry.name));const grantedNames=new Set(grantedSpells(c).map(entry=>entry.spell.Name));const prepareOptions=bookSpells.filter(spell=>spell.Level>=1&&!preparedNames.has(spell.Name)&&!grantedNames.has(spell.Name)).sort((a,b)=>a.Level-b.Level||a.Name.localeCompare(b.Name,"zh-CN"));
  const prepare=()=>{const spell=parseSpell(prepareValue);if(!spell||!limits)return;const occupied=new Set(c.spells.filter(entry=>entry.spellContext==="法师"&&entry.spellRole==="手动准备").map(entry=>Number(entry.slotKey?.split(":").at(-1))||0));const index=Array.from({length:limits.prepared},(_,i)=>i+1).find(number=>!occupied.has(number));if(!index){alert(`当前等级最多准备 ${limits.prepared} 道法术。`);return}onChange([...c.spells,{id:uid(),name:spell.Name,detail:`${sourceLabel(spell.Level)} · ${spellDamage(spell.Description,c.level)} · ${spellSave(spell.Description,c.level)}`,note:spell.Description,quantity:1,level:spell.Level,source:spell.Source,used:false,spellRole:"手动准备",spellContext:"法师",slotKey:`prepared:${index}`}]);setPrepareValue("")};
  const filled=slots.filter(slot=>entries.some(entry=>entry.slotKey===slot.key)).length;const copied=entries.filter(entry=>entry.spellRole==="法术书·抄录");
  return <div className="wizard-spellbook"><header><div><b>法师法术书</b><small>升级所得法术按批次录入；冒险抄录不占升级名额。</small></div><span>{filled}/{slots.length} 个成长栏位 · 共 {bookSpells.length} 道</span></header><div className="spellbook-controls"><label>收录批次<select value={selectedGroup?.key||""} onChange={event=>setGroupKey(event.target.value)}>{groups.map(group=><option key={group.key} value={group.key}>{group.label}</option>)}</select></label>{selectedGroup?.slots.map(slot=>{const current=entries.find(entry=>entry.slotKey===slot.key);return <label key={slot.key}>{slot.label}<select value={current?`${current.source}\u001f${current.name}`:""} onChange={event=>setSlot(slot,event.target.value)}><option value="">尚未收录</option>{availableForSlot(slot).map(spell=><option key={`${spell.Source}-${spell.Name}`} value={valueOf(spell)} disabled={entries.some(entry=>entry.slotKey!==slot.key&&entry.name===spell.Name)}>{sourceLabel(spell.Level)} · {spell.Name} · {spell.Source}</option>)}</select></label>})}</div><div className="spellbook-actions"><div><b>冒险抄录</b><span><select aria-label="选择要抄录的法术" value={copyValue} onChange={event=>setCopyValue(event.target.value)}><option value="">选择法术</option>{copyable.map(spell=><option key={`${spell.Source}-${spell.Name}`} value={valueOf(spell)}>{sourceLabel(spell.Level)} · {spell.Name} · {spell.Source}</option>)}</select><button disabled={!copyValue} onClick={addCopy}><Plus/>抄录</button></span></div><div><b>从法术书准备</b><span><select aria-label="选择要准备的法术" value={prepareValue} onChange={event=>setPrepareValue(event.target.value)}><option value="">选择法术</option>{prepareOptions.map(spell=><option key={`${spell.Source}-${spell.Name}`} value={valueOf(spell)}>{sourceLabel(spell.Level)} · {spell.Name}</option>)}</select><button disabled={!prepareValue} onClick={prepare}><Plus/>准备</button></span></div></div>{copied.length>0&&<div className="copied-spells">{copied.map(entry=><span key={entry.id}><b>{sourceLabel(entry.level||0)} · {entry.name}</b><button aria-label={`移除抄录法术 ${entry.name}`} onClick={()=>commit(c.spells.filter(spell=>spell.id!==entry.id))}><X/></button></span>)}</div>}</div>;
}

function EditableRows({rows,onChange,kind,character}:{rows:RowEntry[];onChange:(r:RowEntry[])=>void;kind:"attack"|"item";character?:Character}){
  const weapons=[...BASE_WEAPONS,...RULES.Weapons.filter(x=>character&&allowed(x.Source,character.enabledSources)&&(!x.RequiredSpecies||x.RequiredSpecies===character.species))];
  const items=EQUIPMENT.filter(x=>!character||allowed(x.Source,character.enabledSources));
  const suggestions=kind==="attack"?weapons.map(x=>x.Name):items.map(x=>x.Name);
  const edit=(id:string,patch:Partial<RowEntry>)=>onChange(rows.map(x=>x.id===id?{...x,...patch}:x));
  const changeName=(row:RowEntry,name:string)=>{
    if(kind==="item"){
      const item=items.find(x=>x.Name===name);
      if(item){
        edit(row.id,{name,itemCategory:item.Category,price:item.Price,weight:item.Weight,detail:[item.Category,item.Price,item.Weight].filter(Boolean).join(" · "),note:item.Description});
        return;
      }
      edit(row.id,{name,itemCategory:row.itemCategory||"自定义"});
      return;
    }
    const rule=weapons.find(x=>x.Name===name);
    edit(row.id,rule?{name,detail:"规则武器",attackRoll:undefined,damage:undefined,damageType:undefined,properties:undefined,mastery:undefined}:{name,detail:name?"玩家手动录入":""});
  };
  const editItem=(row:RowEntry,patch:Partial<RowEntry>)=>{
    const currentParts=row.detail.split(" · ");
    const next={...row,itemCategory:row.itemCategory||currentParts[0]||"",price:row.price||currentParts[1]||"",weight:row.weight||currentParts[2]||"",...patch};
    edit(row.id,{...patch,detail:[next.itemCategory,next.price,next.weight].filter(Boolean).join(" · ")});
  };
  const weaponValues=(row:RowEntry)=>{
    const rule=weapons.find(x=>x.Name===row.name);
    if(!rule||!character)return {
      attack:row.attackRoll||"—",
      damage:[row.damage,row.damageType].filter(Boolean).join(" ")||"—",
      traits:row.properties||"自定义武器",
      mastery:row.mastery?`精通 ${row.mastery}`:"—"
    };
    const enhancement=row.enhancement||0;
    const result=weaponAttackResolution(character,rule,enhancement,false);
    return {
      attack:`d20${signed(result.attackBonus)}`,
      damage:`${rule.Damage}${result.damageBonus?signed(result.damageBonus):""} ${rule.DamageType}`.trim(),
      traits:[rule.Category,rule.Properties,result.proficient?"熟练":"未熟练",rule.Mastery&&`精通 ${rule.Mastery}`].filter(Boolean).join(" · "),
      mastery:result.masteryState==="enabled"?rule.MasteryEffect||"已启用":result.masteryState==="requiresSelection"?"精通待选择":"精通未生效",
      masteryState:result.masteryState,
      tooltip:result.tooltip
    };
  };
  return <div className="row-list">
    {rows.map(row=>{
      const weaponRule=kind==="attack"?weapons.find(x=>x.Name===row.name):null;
      const weapon=kind==="attack"?weaponValues(row):null;
      const detailParts=row.detail.split(" · ");
      const itemCategory=row.itemCategory||detailParts[0]||"";
      const price=row.price||detailParts[1]||"";
      const weight=row.weight||detailParts[2]||"";
      return <article className="edit-row" key={row.id}>
        <div className={`row-main ${kind}`}>
          <input aria-label={kind==="attack"?"武器名称":"物品名称"} list={`${kind}-suggestions`} value={row.name} placeholder={kind==="attack"?"武器名称":"输入名称或关键词"} onChange={e=>changeName(row,e.target.value)}/>
          {kind==="attack"?<>
            <div className="weapon-enhancement"><small>强化</small><NumberBox label={`${row.name||"武器"}强化`} max={9} value={row.enhancement||0} onChange={n=>edit(row.id,{enhancement:n})}/></div>
            <div className="weapon-value"><small>攻击</small><b>{weapon!.attack}</b></div>
            <div className="weapon-value"><small>伤害</small><b>{weapon!.damage}</b></div>
            <div className="weapon-traits" title={weapon!.tooltip}><small>{weapon!.traits}</small><span>{weapon!.mastery}</span></div>
            <label className="weapon-attuned"><input type="checkbox" checked={row.attuned||false} onChange={e=>edit(row.id,{attuned:e.target.checked})}/><span>同调</span></label>
          </>:<>
            <label className="item-field"><small>分类</small><input aria-label={`${row.name||"物品"}分类`} value={itemCategory} placeholder="自定义" onChange={e=>editItem(row,{itemCategory:e.target.value})}/></label>
            <label className="item-field"><small>金额</small><input aria-label={`${row.name||"物品"}金额`} value={price} placeholder="—" onChange={e=>editItem(row,{price:e.target.value})}/></label>
            <label className="item-field"><small>重量</small><input aria-label={`${row.name||"物品"}重量`} value={weight} placeholder="—" onChange={e=>editItem(row,{weight:e.target.value})}/></label>
            <label className="item-field item-note"><small>说明</small><input aria-label={`${row.name||"物品"}说明`} value={row.note} placeholder="道具说明" onChange={e=>edit(row.id,{note:e.target.value})}/></label>
            <NumberBox label={`${row.name||"物品"}数量`} value={row.quantity} onChange={n=>edit(row.id,{quantity:n})}/>
          </>}
          <button className="icon-button danger" aria-label={`删除${row.name||(kind==="attack"?"武器":"物品")}`} onClick={()=>onChange(rows.filter(x=>x.id!==row.id))}><X/></button>
        </div>
        {kind==="attack"&&!weaponRule&&<div className="manual-weapon-fields">
          <label><small>最终攻击</small><input aria-label={`${row.name||"自定义武器"}最终攻击`} value={row.attackRoll||""} placeholder="例如 d20+7" onChange={e=>edit(row.id,{attackRoll:e.target.value})}/></label>
          <label><small>最终伤害</small><input aria-label={`${row.name||"自定义武器"}最终伤害`} value={row.damage||""} placeholder="例如 1d8+4" onChange={e=>edit(row.id,{damage:e.target.value})}/></label>
          <label><small>伤害类型</small><input aria-label={`${row.name||"自定义武器"}伤害类型`} value={row.damageType||""} placeholder="例如 挥砍" onChange={e=>edit(row.id,{damageType:e.target.value})}/></label>
          <label><small>精通</small><input aria-label={`${row.name||"自定义武器"}精通`} value={row.mastery||""} placeholder="例如 迟缓" onChange={e=>edit(row.id,{mastery:e.target.value})}/></label>
          <label className="manual-properties"><small>词条与说明</small><textarea aria-label={`${row.name||"自定义武器"}词条与说明`} value={row.properties||""} placeholder="武器词条、特殊效果或备注" onChange={e=>edit(row.id,{properties:e.target.value})}/></label>
          <p>最终攻击与伤害按 Windows 手动录入逻辑保存，不会再次自动叠加强化值。</p>
        </div>}
      </article>;
    })}
    <datalist id={`${kind}-suggestions`}>{suggestions.map(x=><option key={x} value={x}/>)}</datalist>
    <button className="add-line" onClick={()=>onChange([...rows,{id:uid(),name:"",detail:"",note:"",quantity:1,itemCategory:kind==="item"?"自定义":undefined}])}><Plus/>添加{kind==="attack"?"武器":"物品"}</button>
  </div>;
}

function CharacterNavigation({workspace,onSelect,onAdd,onDuplicate,onDelete,onClose}:{workspace:Workspace;onSelect:(id:string)=>void;onAdd:()=>void;onDuplicate:()=>void;onDelete:()=>void;onClose:()=>void}){
  return <aside className="character-sidebar" aria-label="人物卡导航"><div className="sidebar-brand"><span><BookOpen/></span><div><b>卷册工坊</b><small>iPad 跑团工作区</small></div><button className="sidebar-close" aria-label="关闭人物导航" onClick={onClose}><X/></button></div><div className="sidebar-title"><span><Users/>人物卡</span><button aria-label="新建人物卡" onClick={onAdd}><UserPlus/></button></div><div className="character-list">{workspace.characters.map(character=><button key={character.id} className={character.id===workspace.activeCharacterId?"active":""} onClick={()=>onSelect(character.id)}><span>{character.name.slice(0,1)||"卷"}</span><div><b>{character.name||"未命名人物"}</b><small>{character.species} · {character.className} {character.level}级</small></div></button>)}</div><div className="sidebar-actions"><button onClick={onDuplicate}><Copy/>复制当前人物</button><button className="danger" disabled={workspace.characters.length<=1} onClick={onDelete}><Trash2/>删除当前人物</button></div><p className="sidebar-footnote">人物数据保存在这台设备，可随时导出完整工作区备份。</p></aside>
}

function CombatInline({c,setC,onShortRest,onLongRest}:{c:Character;setC:(c:Character)=>void;onShortRest:()=>void;onLongRest:()=>void}){
  const [hpExpression,setHpExpression]=useState("");
  const [damageNotice,setDamageNotice]=useState("");
  const slots=spellSlots(c.className,c.subclass,c.level), resources=resourceCaps(c), currentSpells=currentCharacterSpells(c), automaticSpells=grantedSpells(c);
  const hpCompact=hpExpression.replace(/\s+/g,"");const hpResult=previewHitPointExpression(c,hpExpression);const hpExpressionValid=hpResult.valid&&Boolean(hpCompact);const hpPreview=hpResult.hp,tempHpPreview=hpResult.tempHp;
  const setUsed=(key:string,n:number)=>setC({...c,resourceMarks:{...c.resourceMarks,[key]:n}});
  const applyHp=()=>{if(!hpCompact)return;if(!hpResult.valid){setDamageNotice("请输入连续的带符号数字，例如 -8+3-2");return}setC({...c,hp:hpPreview,tempHp:tempHpPreview});setDamageNotice(c.activeConditions.includes("专注")&&hpResult.damages.length?`专注豁免：${hpResult.damages.map(d=>`DC ${concentrationSaveDifficulty(d)}`).join("、")}`:"");setHpExpression("")};
  const quickSpells=[...currentSpells.map(entry=>({key:entry.id,name:entry.name,level:entry.level||0,source:entry.spellRole||entry.source||c.className,note:entry.note})),...automaticSpells.filter(auto=>!currentSpells.some(entry=>entry.name===auto.spell.Name&&entry.source===auto.spell.Source)).map(auto=>({key:`auto:${auto.feature}:${auto.spell.Source}:${auto.spell.Name}`,name:auto.spell.Name,level:auto.spell.Level,source:`自动 · ${auto.feature}`,note:auto.spell.Description}))];
  return <section className="sheet-card wide combat-inline-card main-combat-card"><header className="card-head"><span><Swords/></span><h2>生命管理</h2><div className="rest-actions"><button className="text-button" title="恢复短休资源与契术法术位" onClick={onShortRest}><RotateCcw/>短休</button><button className="text-button long-rest-button" title="恢复生命、法术位与长休资源；力竭不自动消除" onClick={onLongRest}><RotateCcw/>长休</button></div></header><div className="combat-inline"><div className="combat-health"><div className="current-hp"><small>当前生命</small><b>{hpExpressionValid?hpPreview:c.hp}</b><span>/ {maxHp(c)}</span></div><div className="hp-expression"><label>生命变化<input value={hpExpression} onChange={e=>setHpExpression(e.target.value)} onBlur={applyHp} onKeyDown={e=>{if(e.key==="Enter")applyHp()}} placeholder="例如 -7+2-1"/></label><small>{hpExpression?hpExpressionValid?`结算后：生命 ${hpPreview} · 临时生命 ${tempHpPreview}`:"格式：-8+3-2；每项依次结算":"回车或移开后记录；伤害先扣临时生命"}</small>{damageNotice&&<strong role="status" className="damage-notice">{damageNotice}</strong>}</div><div className="temp-hp"><span>临时生命</span><NumberBox label="临时生命" value={c.tempHp} onChange={n=>setC({...c,tempHp:n})}/></div></div><div className="inline-resource-groups"><div className="resource-block"><h3>战斗资源</h3>{resources.map(({key,...resource})=><ResourceDots key={key} {...resource} used={c.resourceMarks[key]||0} onChange={n=>setUsed(key,n)}/>)}</div>{Object.entries(slots).length>0&&<div className="resource-block"><h3>法术位</h3>{Object.entries(slots).map(([ring,max])=><ResourceDots key={ring} label={`${ring}环`} max={max} used={c.slotMarks[ring]||0} onChange={n=>setC({...c,slotMarks:{...c.slotMarks,[ring]:n}})}/>)}</div>}</div><div className="inline-spells"><h3>当前职业法术</h3><div className="spell-chips spell-quick-list">{quickSpells.sort((a,b)=>a.level-b.level||a.name.localeCompare(b.name,"zh-CN")).map(x=><article key={x.key}><span>{sourceLabel(x.level)}</span><div><b>{x.name}</b><small>{x.source}</small></div><div className="spell-quick-values"><span><small>伤害</small><b>{spellDamage(x.note,c.level)}</b></span><span><small>豁免</small><b>{spellSave(x.note,c.level)}</b></span></div></article>)}{quickSpells.length===0&&<em>当前职业尚未选择法术</em>}</div></div></div></section>
}

function SummonDrawer({spells,onClose}:{spells:Array<(typeof RULES.Spells)[number]>;onClose:()=>void}){
  return <aside className="summon-drawer" aria-label="召唤物面板"><div className="mobile-sidebar-head"><div><small>法术召唤数据</small><b>召唤物面板</b></div><button aria-label="关闭召唤物面板" onClick={onClose}><X/></button></div>{spells.map(spell=>{const stats=summonStats(spell);return <section className="summon-card" key={`${spell.Source}-${spell.Name}`}><header><div><b>{spell.Name}</b><small>{sourceLabel(spell.Level)} · {spell.Source}</small></div></header><div className="summon-vitals"><span>AC<b>{stats.ac}</b></span><span>HP<b>{stats.hp}</b></span><span>速度<b>{stats.speed}</b></span></div><div className="summon-abilities">{ABILITIES.map(ability=><span key={ability}>{ability}<b>{stats.abilities[ability]}</b></span>)}</div><details><summary>属性、特性与动作规则原文</summary><p>{stats.rules}</p></details></section>})}{spells.length===0&&<p className="empty">尚未开启召唤物面板。</p>}</aside>
}

function LanguagePanel({c,onChange}:{c:Character;onChange:(languages:string[])=>void}){
  const rules=languageRules(c), selected=new Set(rules.selected);
  const toggle=(language:string,checked:boolean)=>{let next=rules.selected.filter(x=>x!==language);if(checked){const rare=RARE_LANGUAGES.includes(language);if(next.length>=rules.totalCap){alert("已达到当前语言自选上限。");return}if(rare&&next.filter(x=>RARE_LANGUAGES.includes(x)).length>=rules.rareCap){alert("稀有语言需要种族、职业或其他特性提供语言选择名额。");return}next=[...next,language]}onChange(next)};
  return <><div className="language-controls"><p className="rule-note">通用语自动掌握；另选 2 门标准语言。种族或职业提供的额外语言名额可用于稀有语言，自动语言不占额度。</p><b>自选 {rules.selected.length}/{rules.totalCap} · 稀有 {rules.rareSelected}/{rules.rareCap}</b></div><div className="language-grid">{[...STANDARD_LANGUAGES,...RARE_LANGUAGES].map(language=>{const automatic=rules.automatic.get(language),rare=RARE_LANGUAGES.includes(language);return <label key={language} className={rare?"rare-language":""} title={automatic?`自动掌握 · ${automatic}`:rare?"需要额外语言选择名额":"标准语言"}><input type="checkbox" disabled={Boolean(automatic)} checked={Boolean(automatic)||selected.has(language)} onChange={e=>toggle(language,e.target.checked)}/><span>{language}{automatic?" · 自动":rare?" · 稀有":""}</span></label>})}</div></>;
}

function CharacterOptionsPanel({c,onChange}:{c:Character;onChange:(next:Character)=>void}){
  const hasMagicInitiate=hasMagicInitiateFeat(c);
  const alternate=alternateFightingStyleFor(c.className);
  const hasStyle=Boolean(alternate&&automaticFeatures(c).some(x=>x.name.includes("战斗风格")));
  if(!hasMagicInitiate&&c.className!=="牧师"&&c.className!=="德鲁伊"&&!hasStyle)return null;
  return <div className="character-options"><b>职业与专长选项</b><div className="form-grid">
    {hasMagicInitiate&&<label>魔法学徒法表<select value={c.magicInitiateClass} onChange={e=>onChange({...c,magicInitiateClass:e.target.value,spells:c.spells.filter(x=>x.spellRole!=="魔法学徒")})}><option value="">请选择</option>{MAGIC_INITIATE_LISTS.map(x=><option key={x}>{x}</option>)}</select></label>}
    {c.className==="牧师"&&c.level>=1&&<label>神圣职能<select value={c.divineOrder} onChange={e=>onChange({...c,divineOrder:e.target.value})}><option value="">请选择</option>{DIVINE_ORDERS.map(x=><option key={x}>{x}</option>)}</select></label>}
    {c.className==="德鲁伊"&&c.level>=1&&<label>原初职能<select value={c.primalOrder} onChange={e=>onChange({...c,primalOrder:e.target.value})}><option value="">请选择</option>{PRIMAL_ORDERS.map(x=><option key={x}>{x}</option>)}</select></label>}
    {hasStyle&&<label>替代战斗风格<select value={c.alternateFightingStyle} onChange={e=>onChange({...c,alternateFightingStyle:e.target.value,manualFeatures:e.target.value?c.manualFeatures.filter(x=>x.detail!=="战斗风格"):c.manualFeatures})}><option value="">保留普通战斗风格</option><option value={alternate}>{alternate}</option></select></label>}
  </div><small>只有需要玩家选择的规则选项显示在这里；随等级获得的职业特性自动加入。</small></div>;
}

function ConditionPanel({c,onChange}:{c:Character;onChange:(next:Character)=>void}){
  return <div className="condition-panel"><header><b>状态与力竭</b><span>豁免、攻击与速度会按规则修正</span></header><div className="condition-list">{Object.entries(CONDITION_DEFINITIONS).map(([name,description])=><label key={name} title={description}><input type="checkbox" checked={c.activeConditions.includes(name)} onChange={e=>onChange(setCondition(c,name,e.target.checked))}/><span>{name}</span></label>)}</div><div className="exhaustion-control"><span>力竭等级</span><NumberBox label="力竭等级" min={0} max={6} value={c.exhaustionLevel} onChange={n=>onChange({...c,exhaustionLevel:normalizeExhaustion(n)})}/><small>{c.exhaustionLevel?`D20 检定 -${exhaustionD20Penalty(c.exhaustionLevel)}；6 级死亡。休息不自动清除力竭。`:"无力竭"}</small></div></div>;
}

function WeaponTrainingPanel({c,onChange}:{c:Character;onChange:(names:string[])=>void}){
  const [candidate,setCandidate]=useState("");
  const options=[...new Set([...BASE_WEAPONS,...RULES.Weapons.filter(x=>allowed(x.Source,c.enabledSources)&&(!x.RequiredSpecies||x.RequiredSpecies===c.species))].map(x=>x.Name))].filter(name=>!c.additionalWeaponProficiencies.includes(name)).sort((a,b)=>a.localeCompare(b,"zh-CN"));
  return <div className="weapon-training"><b>额外武器熟练</b><div className="training-add"><select aria-label="选择额外熟练武器" value={candidate} onChange={e=>setCandidate(e.target.value)}><option value="">选择单项武器</option>{options.map(name=><option key={name}>{name}</option>)}</select><button disabled={!candidate} onClick={()=>{onChange([...c.additionalWeaponProficiencies,candidate]);setCandidate("")}}><Plus/>添加</button></div><div className="training-chips">{c.additionalWeaponProficiencies.map(name=><span key={name}>{name}<button aria-label={`移除${name}熟练`} onClick={()=>onChange(c.additionalWeaponProficiencies.filter(x=>x!==name))}><X/></button></span>)}</div><small>职业自带熟练自动计算；这里只添加额外获得的单项武器熟练。</small></div>;
}

function CustomArmorPanel({c,onChange}:{c:Character;onChange:(next:Character)=>void}){
  const update=(id:string,patch:Partial<Character["customArmors"][number]>)=>onChange({...c,customArmors:c.customArmors.map(x=>x.id===id?{...x,...patch}:x)});
  const rename=(armor:Character["customArmors"][number],input:HTMLInputElement)=>{
    const name=input.value.trim();
    if(!name||armorOptions(c).some(x=>x.Name===name&&name!==armor.name)||c.customArmors.some(x=>x.id!==armor.id&&x.name===name)){
      input.value=armor.name;alert("护甲名称不能为空，也不能与已有护甲重名。");return;
    }
    if(name!==armor.name)onChange({...c,armorName:c.armorName===armor.name?name:c.armorName,customArmors:c.customArmors.map(x=>x.id===armor.id?{...x,name}:x)});
  };
  const add=()=>{
    let index=1;while(armorOptions(c).some(x=>x.Name===`自定义护甲 ${index}`))index++;
    const armor={id:uid(),name:`自定义护甲 ${index}`,category:"轻甲" as const,baseAc:11,dexterityRule:"全部敏捷调整值" as const,strengthRequirement:0,stealthDisadvantage:false,description:""};
    onChange({...c,customArmors:[...c.customArmors,armor],armorName:armor.name,armorEnhancement:0,armorAttuned:false});
  };
  return <div className="custom-armor-panel"><header><b>手动 AC 与自定义护甲</b></header>
    <label className="effect-toggle"><input type="checkbox" checked={c.useManualAc} onChange={e=>onChange({...c,useManualAc:e.target.checked,manualAc:e.target.checked&&c.manualAc<=0?armorClass(c).value:c.manualAc})}/><span>手动指定最终 AC（启用后不再叠加护甲、盾牌或法术修正）</span></label>
    {c.useManualAc&&<div className="control-label"><span>最终 AC</span><NumberBox label="手动 AC" min={0} max={99} value={c.manualAc} onChange={n=>onChange({...c,manualAc:n})}/></div>}
    <details><summary>自定义护甲（{c.customArmors.length}）</summary><div className="custom-armor-list">
      {c.customArmors.map(armor=><div className="custom-armor-row" key={armor.id}>
        <label>名称<input key={armor.name} defaultValue={armor.name} onBlur={e=>rename(armor,e.currentTarget)} onKeyDown={e=>{if(e.key==="Enter")e.currentTarget.blur()}}/></label>
        <label>类别<select value={armor.category} onChange={e=>update(armor.id,{category:e.target.value as typeof armor.category})}><option>轻甲</option><option>中甲</option><option>重甲</option></select></label>
        <div className="control-label"><span>基础 AC</span><NumberBox label={`${armor.name}基础 AC`} value={armor.baseAc} onChange={n=>update(armor.id,{baseAc:n})}/></div>
        <label>敏捷加值<select value={armor.dexterityRule} onChange={e=>update(armor.id,{dexterityRule:e.target.value as typeof armor.dexterityRule})}><option>全部敏捷调整值</option><option>最多+2</option><option>不计敏捷</option></select></label>
        <div className="control-label"><span>力量要求</span><NumberBox label={`${armor.name}力量要求`} value={armor.strengthRequirement} onChange={n=>update(armor.id,{strengthRequirement:n})}/></div>
        <label className="effect-toggle"><input type="checkbox" checked={armor.stealthDisadvantage} onChange={e=>update(armor.id,{stealthDisadvantage:e.target.checked})}/><span>隐匿劣势</span></label>
        <label className="custom-armor-description">说明<input value={armor.description} onChange={e=>update(armor.id,{description:e.target.value})}/></label>
        <button className="icon-button danger" aria-label={`删除自定义护甲 ${armor.name}`} onClick={()=>{if(confirm(`删除自定义护甲“${armor.name}”？`))onChange({...c,customArmors:c.customArmors.filter(x=>x.id!==armor.id),armorName:c.armorName===armor.name?"无甲":c.armorName})}}><Trash2/></button>
      </div>)}
      <button className="add-line" onClick={add}><Plus/>添加并穿上自定义护甲</button>
    </div></details>
  </div>;
}

function SupplementalSpellPanel({c,onChange}:{c:Character;onChange:(spells:RowEntry[])=>void}){
  const choices=grantedCantripChoices(c);
  const hasMagicInitiate=hasMagicInitiateFeat(c)&&Boolean(c.magicInitiateClass);
  if(!choices.length&&!hasMagicInitiate)return null;
  const setSlot=(slotKey:string,role:string,spellList:string,level:number,value:string)=>{
    const remaining=c.spells.filter(entry=>entry.slotKey!==slotKey);
    if(!value){onChange(remaining);return}
    const [source,name]=value.split("\u001f");const spell=RULES.Spells.find(x=>x.Name===name&&x.Source===source&&x.Level===level&&x.Classes?.includes(spellList));
    if(!spell)return;
    if(remaining.some(entry=>entry.spellRole===role&&entry.spellContext===spellList&&entry.name===spell.Name)){alert("该法术已占用同类选择栏位。");return}
    onChange([...remaining,{id:uid(),name:spell.Name,detail:`${role} · ${sourceLabel(level)} · ${spell.Source}`,note:spell.Description,quantity:1,level,source:spell.Source,used:false,spellRole:role,spellContext:spellList,slotKey}]);
  };
  const selector=(slotKey:string,role:string,spellList:string,level:number,label:string)=>{
    const current=c.spells.find(entry=>entry.slotKey===slotKey);
    const options=RULES.Spells.filter(spell=>spell.Level===level&&spell.Classes?.includes(spellList)&&allowed(spell.Source,c.enabledSources)).sort((a,b)=>a.Name.localeCompare(b.Name,"zh-CN"));
    return <label key={slotKey}>{label}<select value={current?`${current.source}\u001f${current.name}`:""} onChange={e=>setSlot(slotKey,role,spellList,level,e.target.value)}><option value="">尚未选择</option>{options.map(spell=><option key={`${spell.Source}-${spell.Name}`} value={`${spell.Source}\u001f${spell.Name}`} disabled={c.spells.some(entry=>entry.slotKey!==slotKey&&entry.spellRole===role&&entry.spellContext===spellList&&entry.name===spell.Name)}>{spell.Name} · {spell.Source}</option>)}</select></label>;
  };
  return <div className="supplemental-spells"><b>专长与职业额外法术</b><div className="spellbook-controls">
    {hasMagicInitiate&&<>{[1,2].map(i=>selector(`magic-initiate:cantrip:${i}`,"魔法学徒",c.magicInitiateClass,0,`魔法学徒戏法 ${i}`))}{selector("magic-initiate:level1","魔法学徒",c.magicInitiateClass,1,"魔法学徒一环法术")}{(()=>{const entry=c.spells.find(x=>x.slotKey==="magic-initiate:level1");return entry?<label className="effect-toggle"><input type="checkbox" checked={Boolean(entry.used)} onChange={e=>onChange(c.spells.map(x=>x.id===entry.id?{...x,used:e.target.checked}:x))}/><span>本次长休已用免费施法（仍可消耗法术位）</span></label>:null})()}</>}
    {choices.flatMap(choice=>Array.from({length:choice.count},(_,i)=>{const prefix=choice.role==="圣职戏法"?"divine-order":choice.role==="原初职能戏法"?"primal-order":"alternate-style";return selector(`grant:${prefix}:${i+1}`,choice.role,choice.spellList,0,`${choice.role} ${i+1}`)}))}
  </div></div>;
}

function FeatureSidebar({c,featureEntries,compact,onToggleCompact,onChange,onClose}:{c:Character;featureEntries:Array<{name:string;description:string;owner:string;source:string}>;compact:boolean;onToggleCompact:()=>void;onChange:(rows:RowEntry[])=>void;onClose:()=>void}){
  const editableFeatures=c.manualFeatures.filter(x=>!x.detail.startsWith("专长选择·"));
  const systemChoices=c.manualFeatures.filter(x=>x.detail.startsWith("专长选择·"));
  const updateEditable=(rows:RowEntry[])=>onChange([...systemChoices,...rows]);
  const edit=(id:string,patch:Partial<RowEntry>)=>updateEditable(editableFeatures.map(x=>x.id===id?{...x,...patch}:x));
  const addManualFeature=()=>onChange([...c.manualFeatures,{id:uid(),name:"",detail:"",note:"",quantity:1}]);
  const background=RULES.Backgrounds.find(x=>x.Name===c.background&&allowed(x.Source,c.enabledSources));
  const originFeat=background?.OriginFeat||(background?.OriginFeatOptions?.includes(c.backgroundOriginFeatChoice)?c.backgroundOriginFeatChoice:"");
  const fightingStyles=RULES.Feats.filter(x=>x.Category==="战斗风格"&&allowed(x.Source,c.enabledSources)).sort((a,b)=>a.Name.localeCompare(b.Name,"zh-CN"));
  const canChooseStyle=!c.alternateFightingStyle&&RULES.ClassFeatures.some(x=>x.ClassName===c.className&&x.Level<=c.level&&x.Name.includes("战斗风格")&&allowed(x.Source,c.enabledSources));
  const generalFeats=RULES.Feats.filter(x=>x.Name!=="属性值提升"&&x.Category.startsWith("通用专长")&&allowed(x.Source,c.enabledSources)).sort((a,b)=>a.Name.localeCompare(b.Name,"zh-CN"));
  const featNodes=featAdvancementNodes(c);
  const addStyle=(name:string)=>{const feat=fightingStyles.find(x=>x.Name===name);if(!feat||c.manualFeatures.some(x=>x.name===feat.Name&&x.detail==="战斗风格"))return;onChange([...c.manualFeatures,{id:uid(),name:feat.Name,detail:"战斗风格",note:feat.Description,quantity:1,source:feat.Source}])};
  const chooseFeat=(node:(typeof featNodes)[number],value:string)=>{const detail=`专长选择·${node.level}级`;const remaining=c.manualFeatures.filter(x=>x.slotKey!==node.key);if(!value){onChange(remaining);return}if(value==="__asi"){onChange([...remaining,{id:uid(),name:"属性值提升",detail,level:node.level,note:"该等级节点选择属性值提升；请在属性区域记录调整后的最终属性值。",quantity:1,source:node.source,slotKey:node.key}]);return}const feat=generalFeats.find(x=>x.Name===value);if(feat)onChange([...remaining,{id:uid(),name:feat.Name,detail,level:node.level,note:[feat.Prerequisite&&`前置条件：${feat.Prerequisite}`,feat.Description].filter(Boolean).join("\n"),quantity:1,source:feat.Source,slotKey:node.key}])};
  return <aside className="feature-sidebar" aria-label="特性与能力侧栏">
    <div className="mobile-sidebar-head"><div><small>人物能力面板</small><b>特性与能力</b></div><button aria-label="关闭能力侧栏" onClick={onClose}><X/></button></div>
    <section className="sidebar-section recorded-features">
      <header><span><BookOpen/>额外录入能力</span><small>{editableFeatures.length} 项</small><button onClick={addManualFeature}><Plus/>手动</button></header>
      <div className="recorded-list">
        {editableFeatures.map(row=><article key={row.id}><input aria-label="能力名称" value={row.name} placeholder="能力名称" onChange={e=>edit(row.id,{name:e.target.value})}/><input aria-label="能力来源" value={row.detail} placeholder="来源 / 等级" onChange={e=>edit(row.id,{detail:e.target.value})}/><textarea aria-label="能力说明" value={row.note} placeholder="规则说明" onChange={e=>edit(row.id,{note:e.target.value})}/><button className="icon-button danger" aria-label={`删除能力 ${row.name||"未命名"}`} onClick={()=>updateEditable(editableFeatures.filter(x=>x.id!==row.id))}><Trash2/></button></article>)}
        {editableFeatures.length===0&&<p className="empty sidebar-empty">职业、子职、种族和背景能力会按规则自动加入；这里只记录规则外的自定义能力。</p>}
        {editableFeatures.length>0&&<button className="add-line" onClick={addManualFeature}><Plus/>继续录入能力</button>}
      </div>
    </section>
    <section className="sidebar-section">
      <header><span><Sparkles/>自动特性与规则选择</span><button onClick={onToggleCompact}>{compact?"展开说明":"缩略显示"}</button></header>
      <div className="feature-pickers"><p className="rule-note">职业、子职、种族与背景能力随等级自动加入；只有规则要求玩家决定的项目需要在这里选择。</p><div className="origin-feat"><small>起源专长 · 背景自动关联</small><b>{originFeat||"当前背景暂无 2024 关联数据"}</b></div><label>战斗风格<select disabled={!canChooseStyle} defaultValue="" onChange={e=>{addStyle(e.target.value);e.currentTarget.value=""}}><option value="">{canChooseStyle?"选择并录入战斗风格":"当前职业等级未解锁"}</option>{fightingStyles.map(x=><option key={`${x.Source}-${x.Name}`} value={x.Name}>{x.Name}</option>)}</select></label>{featNodes.length>0&&<div className="feat-advancement"><b>属性值提升／通用专长</b><small>每个已解锁节点只能二选一。</small>{featNodes.map(node=>{const current=c.manualFeatures.find(x=>x.slotKey===node.key);const value=current?.name==="属性值提升"?"__asi":current?.name||"";const unavailable=Boolean(current&&current.name!=="属性值提升"&&!generalFeats.some(x=>x.Name===current.name));return <label key={node.key}><span>{node.label}</span><select value={value} onChange={e=>chooseFeat(node,e.target.value)}><option value="">尚未选择</option><option value="__asi">属性值提升</option>{unavailable&&<option value={current!.name}>⚠ {current!.name}（来源未启用）</option>}{generalFeats.map(x=><option key={`${x.Source}-${x.Name}`} value={x.Name}>{x.Name}</option>)}</select></label>})}</div>}</div>
      <div className={`features ${compact?"compact":""}`}>{featureEntries.map((x,i)=><details key={`${x.source}-${x.owner}-${x.name}-${i}`}><summary><b>{x.name}</b><small>{x.owner===x.name?x.source:`${x.owner} · ${x.source}`}</small><ChevronDown/></summary><p>{x.description}</p></details>)}{featureEntries.length===0&&<p className="empty sidebar-empty">当前人物还没有自动获得的能力。</p>}</div>
    </section>
  </aside>
}

function PrintSnapshot({c}:{c:Character}){
  const ac=armorClass(c),speed=speedValue(c),features=automaticFeatures(c),spells=currentCharacterSpells(c),resources=resourceCaps(c),slots=spellSlots(c.className,c.subclass,c.level);
  const list=(rows:RowEntry[],empty:string)=><ul>{rows.length?rows.map(row=><li key={row.id}><b>{row.name||"未命名"}</b>{row.quantity>1?` ×${row.quantity}`:""}{row.detail?` · ${row.detail}`:""}{row.note&&<small>{row.note}</small>}</li>):<li>{empty}</li>}</ul>;
  return <article className="print-snapshot"><header><div><small>卷册工坊 · 当前人物完整快照</small><h1>{c.name||"未命名人物"}</h1><p>{c.player||"未填写玩家"} · {c.species}{c.subspecies?`／${c.subspecies}`:""} · {c.className} {c.level}级{c.subclass?`／${c.subclass}`:""} · {c.background}</p></div><div className="print-date">{new Date().toLocaleString("zh-CN")}</div></header><section className="print-metrics"><span>生命<b>{c.hp}/{maxHp(c)}{c.tempHp?` +${c.tempHp}临时`:""}</b></span><span>AC<b>{ac.value}</b></span><span>速度<b>{speed.value}尺</b></span><span>熟练<b>+{proficiency(c.level)}</b></span><span>先攻<b>{signed(initiative(c))}</b></span><span>被动察觉<b>{passivePerception(c)}</b></span></section><div className="print-columns"><section><h2>属性与技能</h2><div className="print-abilities">{ABILITIES.map(ability=><span key={ability}>{ability}<b>{c.abilities[ability]}（{signed(modNumber(c.abilities[ability]))}）</b></span>)}</div><p>{Object.entries(SKILL_ABILITY).map(([name,ability])=>`${name}${skillDisadvantageSources(c,name).length?"（劣势）":""} ${signed(modNumber(c.abilities[ability])+skillTrainingBonus(c,c.skillRanks[name]||0)-exhaustionD20Penalty(c.exhaustionLevel))}`).join(" · ")}</p></section><section><h2>防护与资源</h2><p>状态：{c.activeConditions.join("、")||"无"} · 力竭 {c.exhaustionLevel}级（D20 -{exhaustionD20Penalty(c.exhaustionLevel)}）</p><p>{c.armorName}{c.armorEnhancement?` +${c.armorEnhancement}`:""}（{c.armorAttuned?"已同调":"未同调"}） · {c.shieldName?`${c.shieldName}${c.shieldEnhancement?` +${c.shieldEnhancement}`:""}（${c.shieldAttuned?"已同调":"未同调"}）`:"未使用盾牌"}</p><p>{ac.detail}</p><ul>{resources.map(resource=><li key={resource.key}>{resource.label}：{Math.max(0,resource.max-(c.resourceMarks[resource.key]||0))}/{resource.max}{resource.unit||""}</li>)}{Object.entries(slots).map(([ring,max])=><li key={ring}>{ring}环法术位：{Math.max(0,max-(c.slotMarks[ring]||0))}/{max}</li>)}</ul></section><section><h2>武器与攻击</h2>{list(c.attacks,"暂无攻击")}</section><section><h2>装备与钱币</h2><p>铜币 {c.coins.cp} · 银币 {c.coins.sp} · 金币 {c.coins.gp} · 白金币 {c.coins.pp}</p>{list(c.equipment,"暂无装备")}</section><section><h2>特性与能力</h2><ul>{features.map((feature,index)=><li key={`${feature.source}-${feature.name}-${index}`}><b>{feature.name}</b> · {feature.source}<small>{feature.description}</small></li>)}{c.manualFeatures.map(feature=><li key={feature.id}><b>{feature.name}</b>{feature.detail?` · ${feature.detail}`:""}<small>{feature.note}</small></li>)}</ul></section><section><h2>人物法术</h2>{list(spells,"暂无已录入法术")}</section></div><section className="print-notes"><h2>故事和笔记</h2><p>{c.notes||"暂无笔记"}</p></section></article>;
}

export default function Home(){
  const [workspace,setWorkspace]=useState<Workspace>(()=>defaultWorkspace());const [ready,setReady]=useState(false);const [spellQuery,setSpellQuery]=useState("");const [spellRing,setSpellRing]=useState("全部");const [spellSource,setSpellSource]=useState("全部已启用来源");const [spellMode,setSpellMode]=useState<"class"|"equipment">("class");const [equipmentSpellSource,setEquipmentSpellSource]=useState("");const [equipmentCustomSpell,setEquipmentCustomSpell]=useState("");const [selectedSpell,setSelectedSpell]=useState<(typeof RULES.Spells)[number]|null>(null);const [saved,setSaved]=useState(false);const [navigationOpen,setNavigationOpen]=useState(false);const [featureOpen,setFeatureOpen]=useState(false);const [summonOpen,setSummonOpen]=useState(false);const [updateReady,setUpdateReady]=useState(false);const importRef=useRef<HTMLInputElement>(null);
  const swipeStart=useRef<{x:number;y:number}|null>(null);
  const c=workspace.characters.find(x=>x.id===workspace.activeCharacterId)||workspace.characters[0];
  const setC=(next:Character)=>{const candidate={...next,manualFeatures:sanitizeManualFeatures(next)};const validArmor=armorOptions(candidate).some(armor=>armor.Name===candidate.armorName);const validShield=shieldOptions(candidate).some(shield=>shield.Name===candidate.shieldName);const armorName=validArmor?candidate.armorName:"无甲";const shieldName=validShield?candidate.shieldName:"";const normalized={...candidate,armorName,shieldName,shield:Boolean(shieldName),armorEnhancement:armorName==="无甲"?0:Math.max(0,Math.min(9,candidate.armorEnhancement)),shieldEnhancement:shieldName?Math.max(0,Math.min(9,candidate.shieldEnhancement)):0,armorAttuned:armorName==="无甲"?false:candidate.armorAttuned,shieldAttuned:shieldName?candidate.shieldAttuned:false,hp:Math.max(0,Math.min(candidate.hp,maxHp(candidate))),tempHp:Math.max(0,candidate.tempHp),languages:sanitizeLanguageSelections(candidate)};setWorkspace(w=>({...w,characters:w.characters.map(x=>x.id===w.activeCharacterId?{...normalized,updatedAt:new Date().toISOString()}:x)}))};
  const patch=<K extends keyof Character>(key:K,value:Character[K])=>setC({...c,[key]:value});
  useEffect(()=>{const load=()=>{try{const raw=localStorage.getItem(STORE);if(raw)setWorkspace(normalizeWorkspace(JSON.parse(raw)))}catch(error){console.warn("工作区恢复失败",error)}setReady(true)};queueMicrotask(load);navigator.serviceWorker?.register("/sw.js").then(registration=>{if(registration.waiting)setUpdateReady(true);registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="installed"&&navigator.serviceWorker.controller)setUpdateReady(true)})})}).catch(()=>{})},[]);
  useEffect(()=>{if(!ready)return;const t=setTimeout(()=>{try{const previous=localStorage.getItem(STORE);if(previous)localStorage.setItem(BACKUP_STORE,previous);localStorage.setItem(STORE,JSON.stringify(workspace))}catch(error){console.warn("工作区保存失败",error)}},500);return()=>clearTimeout(t)},[workspace,ready]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setNavigationOpen(false);setFeatureOpen(false);setSummonOpen(false)}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);
  const enabled=useMemo(()=>c.enabledSources||[],[c.enabledSources]);const classOptions=useMemo(()=>classes(enabled),[enabled]);
  const speciesOptions=RULES.Species.filter(x=>allowed(x.Source,enabled));const backgrounds=RULES.Backgrounds.filter(x=>allowed(x.Source,enabled));const subclasses=RULES.Subclasses.filter(x=>x.ClassName===c.className&&allowed(x.Source,enabled)&&(c.level>=3||x.Name==="破誓者"));
  const autoFeatures=useMemo(()=>automaticFeatures(c),[c]);
  const featureEntries=useMemo(()=>autoFeatures.flatMap(feature=>featureBenefits(feature.name,feature.description).map(benefit=>({...benefit,owner:feature.name,source:feature.source}))),[autoFeatures]);
  const ac=armorClass(c),speed=speedValue(c),prof=proficiency(c.level),exhaustion=exhaustionD20Penalty(c.exhaustionLevel);const armor=armorOptions(c).find(x=>x.Name===c.armorName);const currentSpells=currentCharacterSpells(c);const automaticSpells=useMemo(()=>grantedSpells(c),[c]);const wizardBookSpells=useMemo(()=>wizardSpellbookSpells(c),[c]);const spellLimits=spellSelectionLimits(c.className,c.subclass,c.level,c.abilities);const maximumSpellLevel=maximumPreparedSpellLevel(c.className,c.subclass,c.level);const castingAbility=spellcastingAbility(c);const castingModifier=modNumber(c.abilities[castingAbility]);
  const summonSpells=useMemo(()=>c.spells.filter(entry=>entry.showSummonPanel).map(entry=>RULES.Spells.find(spell=>spell.Name===entry.name&&spell.Source===entry.source)).filter((spell):spell is (typeof RULES.Spells)[number]=>Boolean(spell&&isSummoningSpell(spell))).filter((spell,index,list)=>list.findIndex(item=>item.Name===spell.Name&&item.Source===spell.Source)===index),[c.spells]);
  const deferredSpellQuery=useDeferredValue(spellQuery.trim().toLocaleLowerCase("zh-CN"));
  const availableSpells=useMemo(()=>RULES.Spells.filter(s=>allowed(s.Source,enabled)&&(spellMode==="equipment"||((s.Level===0||s.Level<=maximumSpellLevel)&&s.Classes?.includes(spellListClass(c.className,c.subclass,s.Level))))),[spellMode,c.className,c.subclass,maximumSpellLevel,enabled]);
  const spellSources=useMemo(()=>["全部已启用来源",...new Set(availableSpells.map(spell=>spell.Source))],[availableSpells]);
  const effectiveSpellSource=spellSources.includes(spellSource)?spellSource:"全部已启用来源";
  const matchingSpells=useMemo(()=>availableSpells.filter(s=>(spellRing==="全部"||String(s.Level)===spellRing)&&(effectiveSpellSource==="全部已启用来源"||s.Source===effectiveSpellSource)&&(!deferredSpellQuery||`${s.Name} ${s.Description} ${s.Source} ${(s.Classes||[]).join(" ")}`.toLocaleLowerCase("zh-CN").includes(deferredSpellQuery))),[availableSpells,spellRing,effectiveSpellSource,deferredSpellQuery]);
  const spellResults=matchingSpells.slice(0,100);
  const saveNow=()=>{try{const previous=localStorage.getItem(STORE);if(previous)localStorage.setItem(BACKUP_STORE,previous);localStorage.setItem(STORE,JSON.stringify(workspace));setSaved(true);setTimeout(()=>setSaved(false),1300)}catch{alert("当前浏览器无法保存人物卡，请立即导出备份。")}};
  const exportFile=async()=>{const envelope={formatVersion:1,exportedAt:new Date().toISOString(),appVersion:"web-ipad-v1",workspace};const name=`卷册工坊-${c.name||"人物卡"}-${new Date().toISOString().slice(0,10)}.juance`;const file=new File([JSON.stringify(envelope,null,2)],name,{type:"application/json"});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:`卷册工坊 · ${c.name}`,text:"卷册工坊人物卡备份",files:[file]});return}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return}const a=document.createElement("a");a.href=window.URL.createObjectURL(file);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>window.URL.revokeObjectURL(a.href),1000)};
  const importFile=async(file:File)=>{try{const next=normalizeWorkspace(JSON.parse(await file.text()));if(!confirm(`导入 ${next.characters.length} 张人物卡并替换当前工作区？\n当前工作区会保留一份本地备份。`))return;const previous=localStorage.getItem(STORE);if(previous)localStorage.setItem(BACKUP_STORE,previous);setWorkspace(next)}catch{alert("无法识别该卷册人物卡文件。")}};
  const selectCharacter=(id:string)=>{setWorkspace(w=>({...w,activeCharacterId:id}));setNavigationOpen(false)};
  const addCharacter=()=>{const next={...defaultWorkspace().characters[0],name:`新人物 ${workspace.characters.length+1}`};setWorkspace(w=>({...w,activeCharacterId:next.id,characters:[...w.characters,next]}));setNavigationOpen(false)};
  const duplicateCharacter=()=>{const now=new Date().toISOString();const id=uid();const next=normalizeWorkspace({schemaVersion:1,activeCharacterId:id,characters:[{...c,id,createdAt:now,name:`${c.name} 副本`,updatedAt:now}]}).characters[0];setWorkspace(w=>({...w,activeCharacterId:next.id,characters:[...w.characters,next]}));setNavigationOpen(false)};
  const deleteCharacter=()=>{if(workspace.characters.length<=1||!confirm(`删除人物卡“${c.name}”？此操作无法撤销。`))return;setWorkspace(w=>{const characters=w.characters.filter(x=>x.id!==c.id);return {...w,characters,activeCharacterId:characters[0].id}});setNavigationOpen(false)};
  const takeShortRest=()=>{if(confirm("进行短休并恢复当前职业符合规则的短休资源？生命、临时生命和力竭不会自动改变。"))setC(completeShortRest(c))};
  const takeLongRest=()=>{if(confirm("进行长休并恢复当前人物的生命值、法术位与长休资源？临时生命归零，力竭及魔法学徒免费施法使用标记不自动改变。"))setC(completeLongRest(c))};
  const applyUpdate=async()=>{const registration=await navigator.serviceWorker?.getRegistration();if(!registration?.waiting)return;let reloading=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!reloading){reloading=true;location.reload()}},{once:true});registration.waiting.postMessage({type:"SKIP_WAITING"})};
  const addSpell=(spell:(typeof RULES.Spells)[number])=>{if(spellMode==="equipment"){if(c.spells.some(x=>x.spellRole==="装备授予法术"&&x.name===spell.Name&&x.source===spell.Source)){alert("这件装备授予的法术已经记录。");return}patch("spells",[...c.spells,{id:uid(),name:spell.Name,detail:`${equipmentSpellSource.trim()||"未注明装备"} · ${sourceLabel(spell.Level)} · ${spell.Source}`,note:spell.Description,quantity:1,level:spell.Level,source:spell.Source,used:false,spellRole:"装备授予法术",slotKey:`equipment:${uid()}`}]);return}if(currentSpells.some(x=>x.name===spell.Name&&x.spellRole!=="装备授予法术"))return;if(!allowed(spell.Source,enabled)||!spell.Classes?.includes(spellListClass(c.className,c.subclass,spell.Level))){alert("该法术不属于当前职业的可用法术表。");return}if(!spellLimits){alert("当前职业与子职尚未获得施法能力。");return}if(spell.Level>maximumSpellLevel){alert(`当前等级最高只能准备 ${maximumSpellLevel} 环法术。`);return}if(automaticSpells.some(entry=>entry.spell.Name===spell.Name)){alert("该法术已由职业或子职自动获得，不需要重复选择。");return}if(c.className==="法师"&&spell.Level>0&&!wizardSpellbookContains(c,spell.Name)){alert("法师只能准备已经收入当前法术书的法术。");return}const role=spell.Level===0?"戏法":"手动准备",limit=spell.Level===0?spellLimits.cantrips:spellLimits.prepared;const occupied=new Set(c.spells.filter(x=>x.spellContext===c.className&&x.spellRole===role).map(x=>Number(x.slotKey?.split(":").at(-1))||0));const index=Array.from({length:limit},(_,i)=>i+1).find(i=>!occupied.has(i));if(!index){alert(spell.Level===0?`当前等级最多选择 ${limit} 道戏法。`:`当前等级最多准备 ${limit} 道法术。`);return}patch("spells",[...c.spells,{id:uid(),name:spell.Name,detail:`${sourceLabel(spell.Level)} · ${spellDamage(spell.Description,c.level)} · ${spellSave(spell.Description,c.level)}`,note:spell.Description,quantity:1,level:spell.Level,source:spell.Source,used:false,spellRole:role,spellContext:c.className,slotKey:`${role==="戏法"?"cantrip":"prepared"}:${index}`}])};
  const addCustomEquipmentSpell=()=>{const name=equipmentCustomSpell.trim();if(!name)return;if(c.spells.some(x=>x.spellRole==="装备授予法术"&&x.name===name&&x.source==="玩家自定义")){alert("这件装备授予的自定义法术已经记录。");return}patch("spells",[...c.spells,{id:uid(),name,detail:`${equipmentSpellSource.trim()||"未注明装备"} · 自定义`,note:"玩家自定义装备授予法术。",quantity:1,level:0,source:"玩家自定义",used:false,spellRole:"装备授予法术",slotKey:`equipment:${uid()}`}]);setEquipmentCustomSpell("")};
  const setSpecialSpell=(slotKey:string,role:"法术精通"|"招牌法术",level:number,value:string)=>{const remaining=c.spells.filter(entry=>!(entry.slotKey===slotKey&&entry.spellContext===c.className));if(!value){patch("spells",remaining);return}const [source,name]=value.split("\u001f");const spell=wizardBookSpells.find(entry=>entry.Source===source&&entry.Name===name&&entry.Level===level);if(!spell)return;patch("spells",[...remaining,{id:uid(),name:spell.Name,detail:`${sourceLabel(level)} · ${spell.Source}`,note:spell.Description,quantity:1,level,source:spell.Source,used:false,spellRole:role,spellContext:c.className,slotKey}])};
  const toggleSummon=(entry:RowEntry)=>{const next=!entry.showSummonPanel;patch("spells",c.spells.map(spell=>spell.id===entry.id?{...spell,showSummonPanel:next}:spell));if(next)setSummonOpen(true)};
  const changeLevel=(level:number)=>{const next={...c,level};next.hp=Math.min(next.hp,maxHp(next));setC(next)};
  const beginSidebarSwipe=(event:React.TouchEvent<HTMLElement>)=>{if(event.touches.length!==1||event.target instanceof Element&&event.target.closest("input,select,textarea,button,[contenteditable=true]")){swipeStart.current=null;return}const touch=event.touches[0];swipeStart.current={x:touch.clientX,y:touch.clientY}};
  const finishSidebarSwipe=(event:React.TouchEvent<HTMLElement>)=>{const start=swipeStart.current;swipeStart.current=null;if(!start||event.changedTouches.length!==1)return;const touch=event.changedTouches[0];const action=sidebarSwipeAction(touch.clientX-start.x,touch.clientY-start.y,window.innerWidth,navigationOpen?"navigation":featureOpen||summonOpen?"right":null);if(action==="open-navigation")setNavigationOpen(true);else if(action==="open-features")setFeatureOpen(true);else if(action==="close-navigation")setNavigationOpen(false);else if(action==="close-right"){setFeatureOpen(false);setSummonOpen(false)}};
  if(!ready)return <main className="boot"><Sparkles/><b>正在展开卷册…</b></main>;
  return <main className="ipad-app" onTouchStart={beginSidebarSwipe} onTouchEnd={finishSidebarSwipe}>
    <header className="appbar"><button className="shell-toggle navigation-toggle" aria-label="打开人物导航" aria-expanded={navigationOpen} onClick={()=>setNavigationOpen(true)}><Menu/></button><div className="brand"><span><BookOpen/></span><div><b>卷册工坊</b><small>iPad 完整测试版 · Web/PWA</small></div></div>{updateReady&&<button className="update-pill" onClick={applyUpdate}>新版本已就绪 · 点击更新</button>}<div className="app-actions"><button aria-label="导入人物卡" onClick={()=>importRef.current?.click()}><Upload/><span>导入</span></button><input ref={importRef} hidden type="file" accept=".json,.juance" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/><button aria-label={saved?"人物卡已保存":"保存人物卡"} onClick={saveNow}><Save/><span>{saved?"已保存":"保存"}</span></button><button aria-label="分享人物卡" onClick={exportFile}><Download/><span>分享</span></button><button aria-label="打印当前人物完整快照" onClick={()=>window.print()}><Printer/><span>打印</span></button>{summonSpells.length>0&&<button aria-label="打开召唤物面板" onClick={()=>setSummonOpen(true)}><PanelRight/><span>召唤物</span></button>}<button aria-label="打开特性与能力栏" aria-expanded={featureOpen} className="combat-button" onClick={()=>setFeatureOpen(true)}><PanelRight/><span>能力栏</span></button></div></header>
    <button className={`shell-scrim ${navigationOpen||featureOpen||summonOpen?"show":""}`} aria-label="关闭侧栏" onClick={()=>{setNavigationOpen(false);setFeatureOpen(false);setSummonOpen(false)}}/>
    <div className="workspace-shell">
    <div className={`navigation-drawer ${navigationOpen?"open":""}`}><CharacterNavigation workspace={workspace} onSelect={selectCharacter} onAdd={addCharacter} onDuplicate={duplicateCharacter} onDelete={deleteCharacter} onClose={()=>setNavigationOpen(false)}/></div>
    <section className="workspace-main">
    <div className="character-strip"><div className="avatar">{c.name.slice(0,1)||"卷"}</div><div><input aria-label="角色名" value={c.name} onChange={e=>patch("name",e.target.value)}/><small>{c.species} · {c.className} {c.level}级 · {workspace.characters.length} 张人物卡</small><small className="gesture-guide">向右横滑打开人物导航 · 向左横滑打开能力栏</small></div><button className="compact-combat-trigger" aria-expanded={featureOpen} onClick={()=>setFeatureOpen(true)}><Sparkles/>特性与能力</button></div>
    <Segmented value={c.activePage} onChange={v=>patch("activePage",v as Character["activePage"])} items={[["character","人物相关",<Shield key="a"/>],["spells","法术相关",<Sparkles key="b"/>],["notes","故事和笔记",<BookOpen key="c"/>]]}/>
    <div className="page-content">
      {c.activePage==="character"&&<div className="character-layout">
        <Section title="核心资料" icon={<BookOpen/>} wide><div className="form-grid"><label>玩家名<input value={c.player} onChange={e=>patch("player",e.target.value)}/></label><label>职业<select value={c.className} onChange={e=>setC({...c,className:e.target.value,subclass:""})}>{classOptions.map(x=><option key={x}>{x}</option>)}</select></label><div className="control-label"><span>等级</span><NumberBox label="等级" min={1} max={20} value={c.level} onChange={changeLevel}/></div><label>子职<select value={c.subclass} onChange={e=>patch("subclass",e.target.value)}><option value="">{c.level<3?"3级开放":"请选择"}</option>{subclasses.map(x=><option key={`${x.Source}-${x.Name}`} value={x.Name}>{x.Name} · {x.Source}</option>)}</select></label><label>种族<select value={c.species} onChange={e=>setC({...c,species:e.target.value,subspecies:"",armorName:"无甲"})}>{speciesOptions.map(x=><option key={`${x.Source}-${x.Name}`} value={x.Name}>{x.Name}</option>)}</select></label><label>亚种<select value={c.subspecies} onChange={e=>patch("subspecies",e.target.value)}><option value="">无</option>{speciesOptions.find(x=>x.Name===c.species)?.Variants?.map(x=><option key={x.Name}>{x.Name}</option>)}</select></label><label>背景<select value={c.background} onChange={e=>setC({...c,background:e.target.value,backgroundOriginFeatChoice:""})}>{backgrounds.map(x=><option key={`${x.Source}-${x.Name}`} value={x.Name}>{x.Name} · {x.OriginFeat||(x.OriginFeatOptions?.join(" / ")||"暂无起源专长")}</option>)}</select></label>{(()=>{const bg=backgrounds.find(x=>x.Name===c.background);return bg?.OriginFeatOptions?.length?<label>起源专长<select value={c.backgroundOriginFeatChoice} onChange={e=>patch("backgroundOriginFeatChoice",e.target.value)}><option value="">请选择</option>{bg.OriginFeatOptions.map(x=><option key={x}>{x}</option>)}</select></label>:<label>起源专长<input readOnly value={bg?.OriginFeat||"当前背景暂无关联数据"}/></label>})()}<label>阵营<input value={c.alignment} onChange={e=>patch("alignment",e.target.value)}/></label></div></Section>
        <CharacterOptionsPanel c={c} onChange={setC}/>
        <section className="metric-row"><div><Shield/><span>AC<small>{ac.detail}</small></span><b>{ac.value}</b></div><div><span className="walk">➶</span><span>速度<small>{speed.detail}</small></span><b>{speed.value}</b></div><div><Sparkles/><span>熟练<small>d{CLASS_HIT_DIE[c.className]||8} × {c.level} 生命骰</small></span><b>+{prof}</b></div><div><Swords/><span>先攻<small>敏捷{[...automaticFeatures(c).map(x=>x.name),...c.manualFeatures.map(x=>x.name)].includes("警戒")?"＋警戒熟练":"调整值"}</small></span><b>{signed(initiative(c))}</b></div><div><Search/><span>被动察觉<small>10＋感知＋察觉训练</small></span><b>{passivePerception(c)}</b></div><div><Sparkles/><span>英雄激励<small>{c.species==="人类"?"种族资源":"人物记录"}</small></span><b>{c.species==="人类"?Math.max(0,1-(c.resourceMarks.heroic||0)):c.inspiration}</b></div></section>
        <WeaponTrainingPanel c={c} onChange={names=>patch("additionalWeaponProficiencies",names)}/>
        <Section title="武器与攻击" icon={<Swords/>} wide><EditableRows kind="attack" character={c} rows={c.attacks} onChange={x=>patch("attacks",x)}/></Section>
        <Section title="装备、钱币与道具" icon={<Package/>} wide><div className="coins"><Coins/>{(["cp","sp","gp","pp"] as const).map(k=><label key={k}>{({cp:"铜币",sp:"银币",gp:"金币",pp:"白金币"})[k]}<NumberBox label={k} max={99999} value={c.coins[k]} onChange={n=>patch("coins",{...c.coins,[k]:n})}/></label>)}</div><EditableRows kind="item" character={c} rows={c.equipment} onChange={x=>patch("equipment",x)}/></Section>
        <CombatInline c={c} setC={setC} onShortRest={takeShortRest} onLongRest={takeLongRest}/>
        <Section title="属性与技能" icon={<Sparkles/>} wide><div className="ability-grid">{ABILITIES.map(a=><div className="ability" key={a}><b>{a}</b><NumberBox label={a} min={1} max={30} value={c.abilities[a]} onChange={n=>patch("abilities",{...c.abilities,[a]:n})}/><strong>{signed(modNumber(c.abilities[a]))}</strong><small>{CLASS_SAVE[c.className]?.includes(a)?`豁免 ${signed(modNumber(c.abilities[a])+prof-exhaustion)}`:`豁免 ${signed(modNumber(c.abilities[a])-exhaustion)}`}</small></div>)}</div><div className="skills">{Object.entries(SKILL_ABILITY).map(([name,ability])=>{const rank=c.skillRanks[name]||0;const total=modNumber(c.abilities[ability])+skillTrainingBonus(c,rank)-exhaustion;const disadvantageSources=skillDisadvantageSources(c,name);return <button key={name} className={[rank?"trained":"",disadvantageSources.length?"disadvantage":""].filter(Boolean).join(" ")} title={disadvantageSources.length?`劣势来源：${disadvantageSources.join("、")}`:undefined} onClick={()=>patch("skillRanks",{...c.skillRanks,[name]:(rank+1)%3})}><span>{rank===2?"专精":rank===1?"熟练":c.className==="吟游诗人"&&c.level>=2?"半熟练":"○"}</span><b>{name}{disadvantageSources.length?"（劣势）":""}</b><strong>{signed(total)}</strong><small>{ability}</small></button>})}</div></Section>
        <Section title="防护与状态" icon={<Shield/>}><div className="control-stack"><label>护甲<select value={c.armorName} onChange={e=>setC({...c,armorName:e.target.value,armorEnhancement:0,armorAttuned:false})}>{armorOptions(c).map(x=><option key={`${x.Source}-${x.Name}`} value={x.Name}>{x.Type} · {x.Name}</option>)}</select></label><div className="inline-controls"><div className="control-label"><span>护甲强化</span><NumberBox label="护甲强化" max={9} value={c.armorEnhancement} onChange={n=>patch("armorEnhancement",n)}/></div><label className="toggle"><input type="checkbox" disabled={c.armorName==="无甲"} checked={c.armorAttuned} onChange={e=>patch("armorAttuned",e.target.checked)}/><span>护甲已同调</span></label></div><label>盾牌<select value={c.shieldName} onChange={e=>setC({...c,shieldName:e.target.value,shield:Boolean(e.target.value),shieldEnhancement:0,shieldAttuned:false})}><option value="">不使用盾牌</option>{shieldOptions(c).map(x=><option key={`${x.Source}-${x.Name}`} value={x.Name}>{x.Name} · {x.Source}</option>)}</select></label><div className="inline-controls"><div className="control-label"><span>盾牌强化</span><NumberBox label="盾牌强化" max={9} value={c.shieldEnhancement} onChange={n=>patch("shieldEnhancement",n)}/></div><label className="toggle"><input type="checkbox" disabled={!c.shieldName} checked={c.shieldAttuned} onChange={e=>patch("shieldAttuned",e.target.checked)}/><span>盾牌已同调</span></label></div><p className="rule-note">{armor?.Properties}{c.shieldName?` · ${shieldOptions(c).find(x=>x.Name===c.shieldName)?.Properties||c.shieldName}`:""}</p><div className="effect-list"><small>记录当前实际生效的法术，也可选择队友、卷轴或装备施加的效果。</small>{SPELL_STAT_EFFECTS.map(effect=>{const onSheet=c.spells.some(x=>x.name===effect.name);return <label className="effect-toggle" key={effect.name} title={effect.note}><input type="checkbox" checked={c.activeSpellEffects.includes(effect.name)} onChange={e=>patch("activeSpellEffects",e.target.checked?[...new Set([...c.activeSpellEffects,effect.name])]:c.activeSpellEffects.filter(n=>n!==effect.name))}/><span>{effect.name}{onSheet?" · 人物法表":""}</span></label>})}</div></div></Section>
        <Section title="额外防护与状态" icon={<Shield/>}><CustomArmorPanel c={c} onChange={setC}/><ConditionPanel c={c} onChange={setC}/></Section>
        <Section title="掌握语言" icon={<BookOpen/>}><LanguagePanel c={c} onChange={languages=>patch("languages",languages)}/></Section>
        <Section title="规则扩展" icon={<BookOpen/>} wide><p className="rule-note">玩家手册2024始终启用；勾选后对应内容才会进入选项。</p><div className="extensions">{EXPANSIONS.map(x=><label key={x}><input type="checkbox" checked={enabled.includes(x)} onChange={e=>patch("enabledSources",e.target.checked?[...enabled,x]:enabled.filter(y=>y!==x))}/><span>{x}</span></label>)}</div></Section>
      </div>}
      {c.activePage==="spells"&&<div className="spell-layout">
        <section className="spell-manager"><Section title="人物法术" icon={<Sparkles/>}>
          {spellLimits&&<div className="spell-overview"><span>施法属性<b>{castingAbility}</b></span><span>法术豁免 DC<b>{8+prof+castingModifier}</b></span><span>法术攻击<b>{signed(prof+castingModifier-exhaustion)}</b></span><span>最高环阶<b>{maximumSpellLevel?`${maximumSpellLevel}环`:"—"}</b></span></div>}
          <div className="selection-summary">{spellLimits?<><span>戏法 {currentSpells.filter(x=>x.spellRole==="戏法").length}/{spellLimits.cantrips}</span><span>准备 {currentSpells.filter(x=>x.spellRole==="手动准备").length}/{spellLimits.prepared}</span></>:<span>当前职业与子职尚未获得施法能力；装备授予法术仍可独立记录</span>}</div>
          <div className="slot-summary">{Object.entries(spellSlots(c.className,c.subclass,c.level)).map(([r,n])=><span key={r}><b>{r}环</b>{n} 个法术位</span>)}</div>
          {automaticSpells.length>0&&<div className="granted-spells"><b>自动获得（不占准备上限）</b>{automaticSpells.map(x=><button key={`${x.feature}-${x.spell.Name}`} onClick={()=>setSelectedSpell(x.spell)}><span>{sourceLabel(x.spell.Level)}</span><div><strong>{x.spell.Name}</strong><small>{x.feature} · {x.level}级 · {x.source}</small></div></button>)}</div>}
          <SupplementalSpellPanel c={c} onChange={spells=>patch("spells",spells)}/>
          {c.className==="法师"&&<WizardSpellbookPanel c={c} onChange={spells=>patch("spells",spells)}/>}
          {c.className==="法师"&&c.level>=18&&<div className="wizard-special-spells"><b>法师高阶法术</b>{[
            {key:"grant:spell-mastery:1",role:"法术精通" as const,level:1,label:"法术精通 · 一环"},
            {key:"grant:spell-mastery:2",role:"法术精通" as const,level:2,label:"法术精通 · 二环"},
            ...(c.level>=20?[{key:"grant:signature:1",role:"招牌法术" as const,level:3,label:"招牌法术 1 · 三环"},{key:"grant:signature:2",role:"招牌法术" as const,level:3,label:"招牌法术 2 · 三环"}]:[])
          ].map(slot=>{const current=c.spells.find(entry=>entry.slotKey===slot.key&&entry.spellContext==="法师");const otherSignature=c.spells.find(entry=>entry.spellRole==="招牌法术"&&entry.slotKey!==slot.key&&entry.spellContext==="法师");return <label key={slot.key}>{slot.label}<select value={current?`${current.source}\u001f${current.name}`:""} onChange={event=>setSpecialSpell(slot.key,slot.role,slot.level,event.target.value)}><option value="">尚未选择</option>{wizardBookSpells.filter(spell=>spell.Level===slot.level).map(spell=><option key={`${spell.Source}-${spell.Name}`} value={`${spell.Source}\u001f${spell.Name}`} disabled={slot.role==="招牌法术"&&otherSignature?.name===spell.Name}>{spell.Name} · {spell.Source}</option>)}</select></label>})}</div>}
          <div className="prepared-list">{currentSpells.map(x=>{const rule=RULES.Spells.find(s=>s.Name===x.name&&s.Source===x.source);const openSpell=()=>setSelectedSpell(rule||null);const rolePrefix=x.spellRole==="装备授予法术"?"装备授予 · ":x.spellRole&&!["戏法","手动准备"].includes(x.spellRole)&&!x.detail.startsWith(x.spellRole)?`${x.spellRole} · `:"";return <article key={x.id}><button className="prepared-spell-open" aria-label={`查看法术 ${x.name}`} onClick={openSpell}><span>{sourceLabel(x.level||0)}</span><div><b>{x.name}</b><small>{rolePrefix}{x.detail} · 贵重材料 {pricedSpellMaterial(x.note)}</small></div></button>{isSummoningSpell(rule)&&<button className={`summon-toggle ${x.showSummonPanel?"active":""}`} aria-label={`${x.showSummonPanel?"关闭":"打开"}召唤物 ${x.name}`} onClick={()=>toggleSummon(x)}><PanelRight/></button>}<button className="icon-button danger" aria-label={`移除法术 ${x.name}`} onClick={()=>patch("spells",c.spells.filter(s=>s.id!==x.id))}><X/></button></article>})}{currentSpells.length===0&&<p className="empty">从右侧法术资料库添加职业法术或装备授予法术。</p>}</div>
        </Section></section>
        <section className="spell-library"><Section title="法术资料库" icon={<Search/>}>
          <div className="spell-mode"><button className={spellMode==="class"?"active":""} onClick={()=>setSpellMode("class")}>职业法表</button><button className={spellMode==="equipment"?"active":""} onClick={()=>setSpellMode("equipment")}>装备授予</button></div>
          {spellMode==="equipment"&&<div className="equipment-spell-editor"><label className="equipment-spell-source">装备／物品名称<input value={equipmentSpellSource} onChange={e=>setEquipmentSpellSource(e.target.value)} placeholder="例如：火焰法杖"/></label><label>规则库外法术<input value={equipmentCustomSpell} onChange={e=>setEquipmentCustomSpell(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")addCustomEquipmentSpell()}} placeholder="输入自定义法术名"/></label><button disabled={!equipmentCustomSpell.trim()} onClick={addCustomEquipmentSpell}><Plus/>直接记录</button></div>}
          <div className="spell-search"><label><Search/><input value={spellQuery} onChange={e=>setSpellQuery(e.target.value)} placeholder="输入名称、说明、职业或来源"/></label><select aria-label="法术来源" value={effectiveSpellSource} onChange={e=>setSpellSource(e.target.value)}>{spellSources.map(source=><option key={source}>{source}</option>)}</select><select aria-label="法术环阶" value={spellRing} onChange={e=>setSpellRing(e.target.value)}><option>全部</option><option value="0">戏法</option>{Array.from({length:9},(_,i)=><option key={i+1} value={i+1}>{i+1}环</option>)}</select></div>
          <p className="spell-result-count">找到 {matchingSpells.length} 条{matchingSpells.length>100?"，显示前 100 条":""}</p><div className="spell-results">{spellResults.map(s=><button key={`${s.Source}-${s.Name}`} className={selectedSpell===s?"selected":""} onClick={()=>setSelectedSpell(s)}><span>{sourceLabel(s.Level)}</span><b>{s.Name}</b><small>{s.Source}</small></button>)}{spellResults.length===0&&<p className="empty">没有符合当前来源、环阶与关键词的法术。</p>}</div>
        </Section>{selectedSpell&&<Section title={selectedSpell.Name} icon={<BookOpen/>}><div className="spell-facts"><span>环位<b>{sourceLabel(selectedSpell.Level)}</b></span><span>伤害<b>{spellDamage(selectedSpell.Description,c.level)}</b></span><span>豁免<b>{spellSave(selectedSpell.Description,c.level)}</b></span><span>成分<b>{spellMeta(selectedSpell.Description,"法术成分")}</b></span><span>贵重材料<b>{pricedSpellMaterial(selectedSpell.Description)}</b></span></div>{(()=>{const prepared=spellMode==="class"&&currentSpells.some(x=>x.name===selectedSpell.Name&&x.spellRole!=="装备授予法术");const needsSpellbook=spellMode==="class"&&c.className==="法师"&&selectedSpell.Level>0&&!wizardSpellbookContains(c,selectedSpell.Name);const automaticallyGranted=spellMode==="class"&&automaticSpells.some(entry=>entry.spell.Name===selectedSpell.Name);const disabled=prepared||needsSpellbook||automaticallyGranted;const label=spellMode==="equipment"?"记录为装备授予法术":prepared?"已准备":needsSpellbook?"先收入法术书":automaticallyGranted?"已自动获得":"加入人物法术";return <button className="prepare-button" disabled={disabled} onClick={()=>addSpell(selectedSpell)}>{disabled?<Check/>:<Plus/>}{label}</button>})()}<p className="spell-description">{selectedSpell.Description}</p></Section>}</section>
      </div>}
      {c.activePage==="notes"&&<div className="notes-layout"><Section title="故事和笔记" icon={<BookOpen/>} wide><textarea className="notes-area" value={c.notes} onChange={e=>patch("notes",e.target.value)} placeholder="记录人物故事、羁绊、线索、战利品与冒险日志……"/><div className="note-footer"><span>最后修改 {new Date(c.updatedAt).toLocaleString("zh-CN")}</span><button onClick={()=>patch("notes","")}><RotateCcw/>清空</button></div></Section></div>}
    </div>
    </section>
    <div className={`feature-drawer ${featureOpen?"open":""}`}><FeatureSidebar c={c} featureEntries={featureEntries} compact={c.compactFeatureDisplay} onToggleCompact={()=>patch("compactFeatureDisplay",!c.compactFeatureDisplay)} onChange={rows=>patch("manualFeatures",rows)} onClose={()=>setFeatureOpen(false)}/></div>
    <div className={`summon-drawer-host ${summonOpen?"open":""}`}><SummonDrawer spells={summonSpells} onClose={()=>setSummonOpen(false)}/></div>
    </div>
    <PrintSnapshot c={c}/>
  </main>
}
